name: Validate Contributions and Ownership

on:
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    contents: read
    pull-requests: write

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Fetch main branch changes
              run: git fetch origin main

            - name: Fetch pull request changes
              run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_branch

            - name: Get PR branch name
              id: pr_branch_name
              run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref pr_branch)" >> $GITHUB_ENV

            - name: Diff changes
              run: git diff origin/main...$BRANCH_NAME -- > diff_output.txt

            - name: Identify deleted lines
              run: grep '^-' diff_output.txt > deleted_lines.txt

            - name: Check deleted lines attribution
              run: |
                  while IFS= read -r line; do
                    file=$(echo "$line" | cut -d ' ' -f 2)
                    original_commit=$(git blame -L "/$line/" origin/main -- "$file" | cut -d ' ' -f 1 | head -n 1)
                    original_author=$(git show -s --format='%an' $original_commit)
                    deleting_author=$(git show -s --format='%an' HEAD)
                    if [ "$original_author" != "$deleting_author" ]; then
                      echo "Deleted line '$line' was originally created by a different contributor"
                      exit 1
                    fi
                  done < deleted_lines.txt

            - name: Validate folder structure and files
              run: |
                  CHAIN_ID_REGEX='^[0-9]+$'
                  TOKEN_ADDRESS_REGEX='^0x[a-fA-F0-9]{40}$'

                  PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")

                  for file in $(git diff --name-only origin/main...$BRANCH_NAME); do
                    IFS='/' read -r -a path_parts <<< "$file"

                    if [[ ${#path_parts[@]} -lt 2 ]]; then
                      echo "Invalid path structure: $file"
                      exit 1
                    fi

                    if ! [[ ${path_parts[0]} =~ $CHAIN_ID_REGEX ]]; then
                      echo "Invalid chain ID folder: ${path_parts[0]}"
                      exit 1
                    fi

                    if ! [[ ${path_parts[1]} =~ $TOKEN_ADDRESS_REGEX ]]; then
                      echo "Invalid token address folder: ${path_parts[1]}"
                      exit 1
                    fi

                    if [[ ${#path_parts[@]} -eq 3 ]]; then
                      case "${path_parts[2]}" in
                        info.json)
                          if ! jq empty "$file"; then
                            echo "Invalid JSON format: $file"
                            exit 1
                          fi
                          ;;
                        logo.png|logo.jpg|logo.jpeg|logo.svg)
                          if ! file "$file" | grep -qE 'image|SVG'; then
                            echo "Invalid logo file: $file"
                            exit 1
                          fi
                          ;;
                        *)
                          echo "Unexpected file: ${path_parts[2]}"
                          exit 1
                          ;;
                      esac
                    fi

                    if git log --pretty=format:"%an" "$file" | grep -v "$PR_AUTHOR" > /dev/null; then
                      echo "Unauthorized change by $PR_AUTHOR to file: $file"
                      exit 1
                    fi
                  done

            - name: Auto-merge PR
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { data: pullRequest } = await github.rest.pulls.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number
                      });

                      if (pullRequest.mergeable_state === 'clean') {
                        await github.rest.pulls.merge({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.issue.number,
                          merge_method: 'squash'
                        });
                        console.log('Pull request merged successfully.');
                      } else {
                        console.log(`Pull Request State: ${pullRequest.mergeable_state}`);
                        core.setFailed('Pull request is not mergeable.');
                      }
